=== migueltav21/TrabalhosFaculdade/PEI/ficha2_ex2/alinea2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="restaurantes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="restaurante" type="restauranteType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="restauranteType">
        <xs:sequence>
            <xs:element name="nome" type="xs:string"/>
            <xs:element name="capacidade">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="10"/>
                        <xs:maxInclusive value="300"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="localidade" type="xs:string"/>
            <xs:element name="telefone">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="9"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:choice minOccurs="0">
                <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[^@]+@[^@]+\.[a-zA-Z]+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="tipo">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="italiano"/>
                    <xs:enumeration value="japones"/>
                    <xs:enumeration value="mexicano"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== migueltav21/TrabalhosFaculdade/PEI/ficha2_ex2/alinea2.xml
<?xml version="1.0" encoding="UTF-8"?>
<restaurantes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="alinea2.xsd">
    <restaurante>
        <nome>Novo rumo</nome>
        <capacidade>100</capacidade>
        <localidade>Maia</localidade>
        <telefone>919222892</telefone>
        <email>novorumo@gmail.com</email>
    </restaurante>
    <restaurante>
        <nome>Mr.Churrasco</nome>
        <capacidade>200</capacidade>
        <localidade>maia</localidade>
        <telefone>987654321</telefone>
    </restaurante>
</restaurantes>
